idf_component_register(
    SRCS
        "queues.c"
        "sensor_task.c"
        "estimator_task.c"
        "flight_task.c"
        "logger_task.c"
        "telemetry_task.c"
    INCLUDE_DIRS "include"
    REQUIRES
        core
        driver
        log
        esp_timer
        imu_lsm9ds1
        baro_bmp280
        gps_m100
        lora_lr02
        flash_log
)
